version: '3'

services:
  nidhogg-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      # Mount directories for input packages and output results
      - ./packages:/data/input
      - ./results:/data/output
      # For troubleshooting, mount the safe_scanner.py file
      - ./safe_scanner.py:/app/safe_scanner.py
    # Default command can be overridden from command line
    command: bash
    # Set resource limits to prevent DoS
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G